# Generated by Django 4.2 on 2023-04-12 19:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_alter_products_price'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='products',
            name='brand_name',
        ),
        migrations.RemoveField(
            model_name='products',
            name='description',
        ),
    ]
